CREATE TABLE IF NOT EXISTS reponse_qcm (
    Id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    EstCorrecte BOOLEAN NOT NULL,
    tentative_id BIGINT UNSIGNED NOT NULL,
    question_id BIGINT UNSIGNED NOT NULL,
    choix_id BIGINT UNSIGNED NOT NULL,
    CreatedAt DATETIME NOT NULL,
    UpdatedAt DATETIME NOT NULL,
    PRIMARY KEY (Id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
