CREATE TABLE IF NOT EXISTS certification (
    Id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    Code VARCHAR(50) NOT NULL,
    UNIQUE KEY uk_certification_code (Code),
    Libelle VARCHAR(200) NOT NULL,
    Type VARCHAR(40) NOT NULL,
    NiveauRncp VARCHAR(10) NULL,
    AutoriteCertificatrice VARCHAR(200) NULL,
    Statut VARCHAR(20) NOT NULL,
    CreatedAt DATETIME NOT NULL,
    UpdatedAt DATETIME NOT NULL,
    PRIMARY KEY (Id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
