CREATE TABLE IF NOT EXISTS critere_observable (
    Id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    Code VARCHAR(100) NOT NULL,
    Libelle TEXT NOT NULL,
    SavoirEtre BOOLEAN NOT NULL,
    competence_id BIGINT UNSIGNED NOT NULL,
    CreatedAt DATETIME NOT NULL,
    UpdatedAt DATETIME NOT NULL,
    PRIMARY KEY (Id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
