CREATE TABLE IF NOT EXISTS progression_sequence (
    Id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    Statut VARCHAR(20) NOT NULL,
    DateDebut DATE NULL,
    eleve_id BIGINT UNSIGNED NOT NULL,
    sequence_id BIGINT UNSIGNED NOT NULL,
    CreatedAt DATETIME NOT NULL,
    UpdatedAt DATETIME NOT NULL,
    PRIMARY KEY (Id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
