CREATE TABLE IF NOT EXISTS palier (
    Id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    Ordre INT NOT NULL,
    Titre VARCHAR(200) NOT NULL,
    Theme VARCHAR(100) NULL,
    ProductionAttendue VARCHAR(255) NULL,
    DossierTechniqueFichier VARCHAR(255) NOT NULL,
    version_parcours_id BIGINT UNSIGNED NOT NULL,
    CreatedAt DATETIME NOT NULL,
    UpdatedAt DATETIME NOT NULL,
    PRIMARY KEY (Id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
