CREATE TABLE IF NOT EXISTS savoir_associe (
    Id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    Libelle TEXT NOT NULL,
    sequence_id BIGINT UNSIGNED NOT NULL,
    CreatedAt DATETIME NOT NULL,
    UpdatedAt DATETIME NOT NULL,
    PRIMARY KEY (Id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
