CREATE TABLE IF NOT EXISTS depot_eleve (
    Id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    Fichier VARCHAR(255) NOT NULL,
    Commentaire TEXT NULL,
    DateDepot DATETIME NOT NULL,
    progression_palier_id BIGINT UNSIGNED NOT NULL,
    activite_id BIGINT UNSIGNED NOT NULL,
    CreatedAt DATETIME NOT NULL,
    UpdatedAt DATETIME NOT NULL,
    PRIMARY KEY (Id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
