CREATE TABLE IF NOT EXISTS seance_competence (
    Id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    seance_id BIGINT UNSIGNED NOT NULL,
    competence_id BIGINT UNSIGNED NOT NULL,
    Role VARCHAR(20) NOT NULL,
    CreatedAt DATETIME NOT NULL,
    UpdatedAt DATETIME NOT NULL,
    PRIMARY KEY (Id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
