CREATE TABLE IF NOT EXISTS groupe (
    Id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    Nom VARCHAR(100) NOT NULL,
    classe_id BIGINT UNSIGNED NOT NULL,
    CreatedAt DATETIME NOT NULL,
    UpdatedAt DATETIME NOT NULL,
    PRIMARY KEY (Id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
