CREATE TABLE IF NOT EXISTS activite (
    Id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    Objectif TEXT NULL,
    Fichier VARCHAR(255) NULL,
    seance_id BIGINT UNSIGNED NOT NULL,
    CreatedAt DATETIME NOT NULL,
    UpdatedAt DATETIME NOT NULL,
    PRIMARY KEY (Id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
