CREATE TABLE IF NOT EXISTS question_qcm (
    Id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    Numero INT NOT NULL,
    Enonce TEXT NOT NULL,
    BonneReponse VARCHAR(5) NOT NULL,
    qcm_id BIGINT UNSIGNED NOT NULL,
    CreatedAt DATETIME NOT NULL,
    UpdatedAt DATETIME NOT NULL,
    PRIMARY KEY (Id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
