-- Migration Forge
-- Name: timestamps_auto_defaults
-- Les horodatages sont desormais geres par la base : CreatedAt prend la date
-- d insertion (DEFAULT CURRENT_TIMESTAMP), UpdatedAt se met a jour a chaque
-- modification (ON UPDATE CURRENT_TIMESTAMP). Les formulaires et les modeles
-- n ont plus a les fournir (retires cote applicatif).

ALTER TABLE activite MODIFY CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, MODIFY UpdatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
ALTER TABLE activite_professionnelle MODIFY CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, MODIFY UpdatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
ALTER TABLE affectation_parcours MODIFY CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, MODIFY UpdatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
ALTER TABLE affectation_professeur_classe MODIFY CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, MODIFY UpdatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
ALTER TABLE annee_scolaire MODIFY CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, MODIFY UpdatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
ALTER TABLE bilan_eleve MODIFY CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, MODIFY UpdatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
ALTER TABLE checklist MODIFY CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, MODIFY UpdatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
ALTER TABLE choix_qcm MODIFY CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, MODIFY UpdatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
ALTER TABLE classe MODIFY CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, MODIFY UpdatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
ALTER TABLE competence MODIFY CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, MODIFY UpdatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
ALTER TABLE connaissance MODIFY CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, MODIFY UpdatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
ALTER TABLE critere_observable MODIFY CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, MODIFY UpdatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
ALTER TABLE depot_eleve MODIFY CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, MODIFY UpdatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
ALTER TABLE eleve MODIFY CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, MODIFY UpdatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
ALTER TABLE evaluation_activite MODIFY CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, MODIFY UpdatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
ALTER TABLE evaluation_critere MODIFY CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, MODIFY UpdatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
ALTER TABLE famille_competence MODIFY CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, MODIFY UpdatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
ALTER TABLE formation MODIFY CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, MODIFY UpdatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
ALTER TABLE groupe MODIFY CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, MODIFY UpdatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
ALTER TABLE indicateur_reussite MODIFY CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, MODIFY UpdatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
ALTER TABLE inscription_eleve MODIFY CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, MODIFY UpdatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
ALTER TABLE item_checklist MODIFY CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, MODIFY UpdatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
ALTER TABLE item_coche MODIFY CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, MODIFY UpdatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
ALTER TABLE niveau_classe MODIFY CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, MODIFY UpdatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
ALTER TABLE palier MODIFY CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, MODIFY UpdatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
ALTER TABLE parcours MODIFY CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, MODIFY UpdatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
ALTER TABLE pole_activite MODIFY CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, MODIFY UpdatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
ALTER TABLE professeur MODIFY CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, MODIFY UpdatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
ALTER TABLE progression_eleve MODIFY CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, MODIFY UpdatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
ALTER TABLE progression_palier MODIFY CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, MODIFY UpdatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
ALTER TABLE qcm MODIFY CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, MODIFY UpdatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
ALTER TABLE question_qcm MODIFY CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, MODIFY UpdatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
ALTER TABLE referentiel_niveau_classe MODIFY CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, MODIFY UpdatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
ALTER TABLE reponse_qcm MODIFY CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, MODIFY UpdatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
ALTER TABLE resultat_attendu MODIFY CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, MODIFY UpdatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
ALTER TABLE scenario MODIFY CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, MODIFY UpdatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
ALTER TABLE section_checklist MODIFY CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, MODIFY UpdatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
ALTER TABLE source MODIFY CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, MODIFY UpdatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
ALTER TABLE starter_welcome MODIFY CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, MODIFY UpdatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
ALTER TABLE tache MODIFY CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, MODIFY UpdatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
ALTER TABLE tentative_qcm MODIFY CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, MODIFY UpdatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
ALTER TABLE version_parcours MODIFY CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, MODIFY UpdatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
ALTER TABLE version_starter MODIFY CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, MODIFY UpdatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
