-- Migration Forge
-- Name: timestamps_python_authority
-- Retrait des DEFAULT CURRENT_TIMESTAMP / ON UPDATE CURRENT_TIMESTAMP poses par
-- timestamps_auto_defaults : Forge veut une autorite UNIQUE = Python (ADR-081).
-- Les modeles posent desormais created_at/updated_at via datetime.now(timezone.utc) ;
-- les fixtures (.sql generes + referentiel_importer NOW()) fournissent aussi les
-- valeurs. Les colonnes redeviennent DATETIME NOT NULL nues (adoption retour-021 F56).

ALTER TABLE activite MODIFY CreatedAt DATETIME NOT NULL, MODIFY UpdatedAt DATETIME NOT NULL;
ALTER TABLE activite_professionnelle MODIFY CreatedAt DATETIME NOT NULL, MODIFY UpdatedAt DATETIME NOT NULL;
ALTER TABLE affectation_parcours MODIFY CreatedAt DATETIME NOT NULL, MODIFY UpdatedAt DATETIME NOT NULL;
ALTER TABLE affectation_professeur_classe MODIFY CreatedAt DATETIME NOT NULL, MODIFY UpdatedAt DATETIME NOT NULL;
ALTER TABLE annee_scolaire MODIFY CreatedAt DATETIME NOT NULL, MODIFY UpdatedAt DATETIME NOT NULL;
ALTER TABLE bilan_eleve MODIFY CreatedAt DATETIME NOT NULL, MODIFY UpdatedAt DATETIME NOT NULL;
ALTER TABLE checklist MODIFY CreatedAt DATETIME NOT NULL, MODIFY UpdatedAt DATETIME NOT NULL;
ALTER TABLE choix_qcm MODIFY CreatedAt DATETIME NOT NULL, MODIFY UpdatedAt DATETIME NOT NULL;
ALTER TABLE classe MODIFY CreatedAt DATETIME NOT NULL, MODIFY UpdatedAt DATETIME NOT NULL;
ALTER TABLE competence MODIFY CreatedAt DATETIME NOT NULL, MODIFY UpdatedAt DATETIME NOT NULL;
ALTER TABLE connaissance MODIFY CreatedAt DATETIME NOT NULL, MODIFY UpdatedAt DATETIME NOT NULL;
ALTER TABLE critere_observable MODIFY CreatedAt DATETIME NOT NULL, MODIFY UpdatedAt DATETIME NOT NULL;
ALTER TABLE depot_eleve MODIFY CreatedAt DATETIME NOT NULL, MODIFY UpdatedAt DATETIME NOT NULL;
ALTER TABLE eleve MODIFY CreatedAt DATETIME NOT NULL, MODIFY UpdatedAt DATETIME NOT NULL;
ALTER TABLE evaluation_activite MODIFY CreatedAt DATETIME NOT NULL, MODIFY UpdatedAt DATETIME NOT NULL;
ALTER TABLE evaluation_critere MODIFY CreatedAt DATETIME NOT NULL, MODIFY UpdatedAt DATETIME NOT NULL;
ALTER TABLE famille_competence MODIFY CreatedAt DATETIME NOT NULL, MODIFY UpdatedAt DATETIME NOT NULL;
ALTER TABLE formation MODIFY CreatedAt DATETIME NOT NULL, MODIFY UpdatedAt DATETIME NOT NULL;
ALTER TABLE groupe MODIFY CreatedAt DATETIME NOT NULL, MODIFY UpdatedAt DATETIME NOT NULL;
ALTER TABLE indicateur_reussite MODIFY CreatedAt DATETIME NOT NULL, MODIFY UpdatedAt DATETIME NOT NULL;
ALTER TABLE inscription_eleve MODIFY CreatedAt DATETIME NOT NULL, MODIFY UpdatedAt DATETIME NOT NULL;
ALTER TABLE item_checklist MODIFY CreatedAt DATETIME NOT NULL, MODIFY UpdatedAt DATETIME NOT NULL;
ALTER TABLE item_coche MODIFY CreatedAt DATETIME NOT NULL, MODIFY UpdatedAt DATETIME NOT NULL;
ALTER TABLE niveau_classe MODIFY CreatedAt DATETIME NOT NULL, MODIFY UpdatedAt DATETIME NOT NULL;
ALTER TABLE palier MODIFY CreatedAt DATETIME NOT NULL, MODIFY UpdatedAt DATETIME NOT NULL;
ALTER TABLE parcours MODIFY CreatedAt DATETIME NOT NULL, MODIFY UpdatedAt DATETIME NOT NULL;
ALTER TABLE pole_activite MODIFY CreatedAt DATETIME NOT NULL, MODIFY UpdatedAt DATETIME NOT NULL;
ALTER TABLE professeur MODIFY CreatedAt DATETIME NOT NULL, MODIFY UpdatedAt DATETIME NOT NULL;
ALTER TABLE progression_eleve MODIFY CreatedAt DATETIME NOT NULL, MODIFY UpdatedAt DATETIME NOT NULL;
ALTER TABLE progression_palier MODIFY CreatedAt DATETIME NOT NULL, MODIFY UpdatedAt DATETIME NOT NULL;
ALTER TABLE qcm MODIFY CreatedAt DATETIME NOT NULL, MODIFY UpdatedAt DATETIME NOT NULL;
ALTER TABLE question_qcm MODIFY CreatedAt DATETIME NOT NULL, MODIFY UpdatedAt DATETIME NOT NULL;
ALTER TABLE referentiel_niveau_classe MODIFY CreatedAt DATETIME NOT NULL, MODIFY UpdatedAt DATETIME NOT NULL;
ALTER TABLE reponse_qcm MODIFY CreatedAt DATETIME NOT NULL, MODIFY UpdatedAt DATETIME NOT NULL;
ALTER TABLE resultat_attendu MODIFY CreatedAt DATETIME NOT NULL, MODIFY UpdatedAt DATETIME NOT NULL;
ALTER TABLE scenario MODIFY CreatedAt DATETIME NOT NULL, MODIFY UpdatedAt DATETIME NOT NULL;
ALTER TABLE section_checklist MODIFY CreatedAt DATETIME NOT NULL, MODIFY UpdatedAt DATETIME NOT NULL;
ALTER TABLE source MODIFY CreatedAt DATETIME NOT NULL, MODIFY UpdatedAt DATETIME NOT NULL;
ALTER TABLE starter_welcome MODIFY CreatedAt DATETIME NOT NULL, MODIFY UpdatedAt DATETIME NOT NULL;
ALTER TABLE tache MODIFY CreatedAt DATETIME NOT NULL, MODIFY UpdatedAt DATETIME NOT NULL;
ALTER TABLE tentative_qcm MODIFY CreatedAt DATETIME NOT NULL, MODIFY UpdatedAt DATETIME NOT NULL;
ALTER TABLE version_parcours MODIFY CreatedAt DATETIME NOT NULL, MODIFY UpdatedAt DATETIME NOT NULL;
ALTER TABLE version_starter MODIFY CreatedAt DATETIME NOT NULL, MODIFY UpdatedAt DATETIME NOT NULL;
