CREATE TABLE IF NOT EXISTS affectation_parcours (
    Id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    DateAffectation DATE NOT NULL,
    Statut VARCHAR(20) NOT NULL,
    version_parcours_id BIGINT UNSIGNED NOT NULL,
    classe_id BIGINT UNSIGNED NOT NULL,
    professeur_id BIGINT UNSIGNED NOT NULL,
    CreatedAt DATETIME NOT NULL,
    UpdatedAt DATETIME NOT NULL,
    PRIMARY KEY (Id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
