CREATE TABLE IF NOT EXISTS dossier_technique (
    Id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    Titre VARCHAR(200) NOT NULL,
    seance_id BIGINT UNSIGNED NOT NULL,
    CreatedAt DATETIME NOT NULL,
    UpdatedAt DATETIME NOT NULL,
    PRIMARY KEY (Id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
