CREATE TABLE IF NOT EXISTS affectation_professeur_classe (
    Id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    Role VARCHAR(100) NULL,
    professeur_id BIGINT UNSIGNED NOT NULL,
    classe_id BIGINT UNSIGNED NOT NULL,
    annee_scolaire_id BIGINT UNSIGNED NOT NULL,
    CreatedAt DATETIME NOT NULL,
    UpdatedAt DATETIME NOT NULL,
    PRIMARY KEY (Id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
