CREATE TABLE IF NOT EXISTS item_coche (
    Id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    CocheEleve BOOLEAN NOT NULL,
    CocheProfesseur BOOLEAN NOT NULL,
    item_id BIGINT UNSIGNED NOT NULL,
    progression_palier_id BIGINT UNSIGNED NOT NULL,
    CreatedAt DATETIME NOT NULL,
    UpdatedAt DATETIME NOT NULL,
    PRIMARY KEY (Id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
