CREATE TABLE IF NOT EXISTS pole_activite (
    Id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    Intitule VARCHAR(250) NOT NULL,
    referentiel_id BIGINT UNSIGNED NOT NULL,
    CreatedAt DATETIME NOT NULL,
    UpdatedAt DATETIME NOT NULL,
    PRIMARY KEY (Id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
