CREATE TABLE IF NOT EXISTS version_starter (
    Id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    Version VARCHAR(20) NOT NULL,
    Statut VARCHAR(20) NOT NULL,
    ActiviteGlissante BOOLEAN NOT NULL,
    OrdreImpose BOOLEAN NOT NULL,
    starter_id BIGINT UNSIGNED NOT NULL,
    CreatedAt DATETIME NOT NULL,
    UpdatedAt DATETIME NOT NULL,
    PRIMARY KEY (Id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
