CREATE TABLE IF NOT EXISTS section_checklist (
    Id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    Numero INT NOT NULL,
    Titre VARCHAR(200) NOT NULL,
    checklist_id BIGINT UNSIGNED NOT NULL,
    CreatedAt DATETIME NOT NULL,
    UpdatedAt DATETIME NOT NULL,
    PRIMARY KEY (Id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
