CREATE TABLE IF NOT EXISTS source (
    Id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    SourceId VARCHAR(100) NOT NULL,
    SourceType VARCHAR(30) NOT NULL,
    SourceFichier VARCHAR(255) NOT NULL,
    SourceNote TEXT NULL,
    referentiel_id BIGINT UNSIGNED NOT NULL,
    CreatedAt DATETIME NOT NULL,
    UpdatedAt DATETIME NOT NULL,
    PRIMARY KEY (Id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
