CREATE TABLE IF NOT EXISTS inscription_eleve (
    Id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    DateInscription DATE NULL,
    CreatedAt DATETIME NOT NULL,
    UpdatedAt DATETIME NOT NULL,
    PRIMARY KEY (Id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
