CREATE TABLE IF NOT EXISTS qcm (
    Id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    FormatReponse TEXT NULL,
    SeuilValidation VARCHAR(20) NOT NULL,
    palier_id BIGINT UNSIGNED NOT NULL,
    CreatedAt DATETIME NOT NULL,
    UpdatedAt DATETIME NOT NULL,
    PRIMARY KEY (Id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
