CREATE TABLE IF NOT EXISTS choix_qcm (
    Id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    Lettre VARCHAR(5) NOT NULL,
    Texte VARCHAR(255) NOT NULL,
    question_id BIGINT UNSIGNED NOT NULL,
    CreatedAt DATETIME NOT NULL,
    UpdatedAt DATETIME NOT NULL,
    PRIMARY KEY (Id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
